version: '3'
services:

  # this is only used in CI
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=local
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/python:/opt
    ports:
      - "5432:5432"

  python:
    build: "./containers/python"
    container_name: python
    command: /bin/bash -c "jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"
    volumes:
      - ./volumes/notebooks:/opt/notebooks
      - ./volumes/static:/opt/static
    ports:
      - "8888:8888"

  fastapi:
    build: "./containers/fastapi"
    container_name: fastapi
    volumes:
      - ./volumes/static:/opt/static
    ports:
      - "8080:8080"

  streamlit:
    build: "./containers/streamlit"
    container_name: streamlit
    ports:
      - "8501:8501"
